baseURL = "https://ahsen.me/"
languageCode = "en-us"
title = "Mehmet Ahsen"
theme = "anatole"
publishDir = "../docs/"

#anatole theme params
[params]
author = "Mehmet Ahsen"
description = "Mehmet's distant corner."
profilePicture = "profile.jpg"
