baseURL = "https://mehmetahsen.de/"

languageCode = "en-us"
title = "Mehmet Ahsen"
theme = "anatole"

#anatole theme params
[params]
author = "Mehmet Ahsen"
description = "Mehmet's distant corner."
profilePicture = "profile.jpg"
