name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules:  true

    - name: Build
      uses: klakegg/actions-hugo@1.0.0
      with:
        source: 'src/'
        target: './' 

    - name: Commit & Push changes
      run: |
        git config --global user.email "mehmet.ahsen@outlook.com"
        git config --global user.name "Mehmet Ahsen"
        git add docs
        git commit -m 'hugo build, github run id: $GITHUB_RUN_ID'
        git push
