name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules:  true

    - name: Build
      uses: klakegg/actions-hugo@1.0.0
      with:
        source: 'src'
        target: 'docs'
        env:    ''

    - name: Commit & Push changes
      run: |
        ls -lah *
        git config --global user.email "mehmet.ahsen@outlook.com"
        git config --global user.name "Mehmet Ahsen"
        git status
        git add docs
        git commit -m "hugo build, github run id: $GITHUB_RUN_ID"; [ $? -eq 1 ] || exit 0
        git push
