name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules:  true

    - name: Build
      uses: klakegg/actions-hugo@1.0.0
      with:
        source: 'src'
        target: 'docs'
        env:    'production'
        image:  'ext-alpine'

    - name: Commit & Push changes
      run: |
        ls -lah *
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add docs
        git commit -m "hugo build, github run id: $GITHUB_RUN_ID"; [ $? -eq 1 ] || exit 0
        git push
